version: '3.8'

services:
  # 1. Base de Datos
  mysql-db:
    image: mysql:8.0
    container_name: tiquetera-mysql
    environment:
      MYSQL_DATABASE: tiqueteradb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tiquetera-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  # 2. Service Discovery (Simulaci贸n de Microservicios)
  eureka-server:
    image: springcloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - tiquetera-net

  # 3. Nuestra Aplicaci贸n Spring Boot
  tiquetera-api:
    build: .
    container_name: tiquetera-api
    ports:
      - "8082:8082"
    environment:
      # Conexi贸n a MySQL del contenedor
      DB_URL: jdbc:mysql://mysql-db:3306/tiqueteradb?allowPublicKeyRetrieval=true&useSSL=false
      DB_USERNAME: sa
      DB_PASSWORD: password
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      # Configuraci贸n Eureka
      EUREKA_URI: http://eureka-server:8761/eureka
      REGISTER_EUREKA: true
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - tiquetera-net

networks:
  tiquetera-net:
    driver: bridge

volumes:
  mysql_data:


